# Generated by Django 4.2.16 on 2024-09-25 15:21

import datetime
from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contato",
        ),
        migrations.AddField(
            model_name="produto",
            name="ativo",
            field=models.BooleanField(default=True, verbose_name="Ativo?"),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 9, 25, 15, 21, 3, 262769, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Data de Criação",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=stdimage.models.StdImageField(
                default=django.utils.timezone.now,
                force_min_size=False,
                upload_to="produtos",
                variations={"thumb": (124, 124)},
                verbose_name="Imagem",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="modificado",
            field=models.DateField(auto_now=True, verbose_name="Data de Atualização"),
        ),
        migrations.AddField(
            model_name="produto",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, max_length=100, verbose_name="Slug"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="estoque",
            field=models.IntegerField(verbose_name="Estoque"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=100, verbose_name="Nome"),
        ),
    ]
