# Generated by Django 4.2.16 on 2024-09-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_contato_produto_ativo_produto_criado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="imagem",
        ),
        migrations.AddField(
            model_name="produto",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="products/"),
        ),
        migrations.AddField(
            model_name="produto",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
