# Generated by Django 4.2.16 on 2024-09-26 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_produto_imagem_produto_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="image",
            new_name="imagem",
        ),
    ]
